// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-OTr4LedCewafR0bU1Dw2qRrTCqp0DY',
    appId: '1:524034203570:web:dc62d9e99bb4a1c7178eab',
    messagingSenderId: '524034203570',
    projectId: 'moneyminder-76276',
    authDomain: 'moneyminder-76276.firebaseapp.com',
    storageBucket: 'moneyminder-76276.appspot.com',
    measurementId: 'G-0E76FTVYJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxuRXyoBIwxwHq20kMd2u1tkcqEmZZWs8',
    appId: '1:524034203570:android:15e9e8562b94eec7178eab',
    messagingSenderId: '524034203570',
    projectId: 'moneyminder-76276',
    storageBucket: 'moneyminder-76276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJyb8ez4AmLx_7Mku5TKmAvpUCNkTY1S4',
    appId: '1:524034203570:ios:596fb483c18eb9bb178eab',
    messagingSenderId: '524034203570',
    projectId: 'moneyminder-76276',
    storageBucket: 'moneyminder-76276.appspot.com',
    iosBundleId: 'com.example.moneyminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJyb8ez4AmLx_7Mku5TKmAvpUCNkTY1S4',
    appId: '1:524034203570:ios:babbe183bd36121c178eab',
    messagingSenderId: '524034203570',
    projectId: 'moneyminder-76276',
    storageBucket: 'moneyminder-76276.appspot.com',
    iosBundleId: 'com.example.moneyminder.RunnerTests',
  );
}
